//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VS2008.rc
//
#define IDR_MAINFRAME                   101
#define IDD_MAKEROM                     106
#define IDB_MAKEROM                     107
#define IDD_MAP                         108
#define IDB_DET0                        109
#define IDD_CHANGELIB                   111
#define IDB_DET1                        112
#define IDD_ABOUT                       113
#define IDR_NSBTX_TEMP_HORI_0A          115
#define IDR_NSBTX_TEMP_HORI_1A          116
#define IDR_NSBTX_TEMP_HORI_08          117
#define IDR_NSBTX_TEMP_HORI_20A         118
#define IDR_NSBTX_TEMP_HORI_00          120
#define IDR_NSBTX_TEMP_SQUA_1D          121
#define IDR_NSBTX_TEMP_SQUA_19          122
#define IDR_NSBTX_TEMP_SQUA_24          123
#define IDR_NSBTX_TEMP_VERT             124
#define IDD_IMPORTBG                    125
#define IDD_ROMINFO                     126
#define IDD_UPDATE                      127
#define IDD_TEXMAPPING                  128
#define IDD_OBJ                         129
#define IDC_EDIT_MR_ROM                 1002
#define IDC_EDIT_MR_NEWROM              1003
#define IDC_BUTTON_MR_ROM               1004
#define IDC_BUTTON_MR_NEWROM            1005
#define IDC_EDIT_MR_MAPSET              1006
#define IDC_BUTTON_MAKEROM              1007
#define IDC_COMBO_CHANGELIB_BG          1010
#define IDC_COMBO_CHANGELIB_BGL         1011
#define IDC_COMBO_CHANGELIB_FGL         1012
#define IDC_COMBO_CHANGELIB_PL          1013
#define IDC_MAP_VSCROLL                 1013
#define IDC_MAP_HSCROLL                 1014
#define IDC_CHECK_MAP_PLANE2            1016
#define IDC_CHECK_MAP_PLANE0            1017
#define IDC_CHECK_MAP_DET               1018
#define IDC_EDIT_ABOUT                  1019
#define IDC_MAP_STOCK_SCROLL            1019
#define IDC_STATIC_MAP                  1020
#define IDC_STATIC_STOCK                1021
#define IDC_MAP_STOCK_HSCROLL           1022
#define IDC_STATIC_MAP_CUR_COORD        1023
#define IDC_STATIC_MAP_CUR_GRID         1024
#define IDC_EDIT_MAP_CUR_GRID0          1025
#define IDC_EDIT_MAP_CUR_GRID1          1026
#define IDC_STATIC_NDSEMU               1026
#define IDC_EDIT_MAP_CUR_GRID2          1027
#define IDC_EDIT_NDSEMU                 1027
#define IDC_BUTTON_NDSEMU               1028
#define IDC_EDIT_MAP_CUR_GRID_BOSS      1028
#define IDC_BUTTON_BEGINEMU             1029
#define IDC_STATIC_MAP_SCALE            1029
#define IDC_STATIC_MAP_THUMBNAIL        1029
#define IDC_COMBO_BGM                   1031
#define IDC_COMBO_BOSS                  1032
#define IDC_RADIO_MAP_PT_GRID           1036
#define IDC_COMBO_IMPORTBG              1037
#define IDC_RADIO_MAP_PT_OBJ            1038
#define IDC_PROGRESS_IMPORTBG           1038
#define IDC_RADIO_MAP_PT_BOSS           1039
#define IDC_CHECK_MAP_ANI               1041
#define IDC_STATIC_IMPORTBG             1042
#define IDC_LIST_MAP_OBJ                1043
#define IDC_EDIT_ROM_TITLE              1044
#define IDC_EDIT1                       1045
#define IDC_BUTTON_DL_TIEBA             1050
#define IDC_BUTTON_DL_GITHUB            1051
#define IDC_BUTTON_CHECK_FOR_UPDATES    1052
#define IDC_STATIC_TEXMAPPING           1057
#define IDC_RADIO_TEXMAPPING_A          1059
#define IDC_RADIO_TEXMAPPING_B          1060
#define IDC_TEXMAPPING_VSCROLL          1061
#define IDC_TEXMAPPING_HSCROLL          1062
#define IDC_BUTTON_TEXMAPPING_COPY      1063
#define IDC_STATIC_TEXMAPPING_DETAIL    1064
#define IDC_CHECK_TEXMAPPING_CLR0       1065
#define IDC_STATIC_MAP_CX               1066
#define IDC_STATIC_MAP_CY               1067
#define IDC_STATIC_TILE                 1068
#define IDC_EDIT_TILE_ANI0              1069
#define IDC_CHECK_HIDE_FOE              1070
#define IDC_CHECK_HIDE_SUP              1071
#define IDC_EDIT_TILE_ANI1              1072
#define IDC_CHECK_HIDE_DOOR             1072
#define IDC_EDIT_TILE_ANI2              1073
#define IDC_CHECK_HIDE_MCTRL            1073
#define IDC_EDIT_TILE_ANI3              1074
#define IDC_CHECK_OBJ_MOVING_ALIGN      1074
#define IDC_BUTTON_OBJ_UP               1075
#define IDC_BUTTON_OBJ_DOWN             1076
#define IDC_BUTTON_OBJ_NEW              1077
#define IDC_BUTTON_OBJ_DELETE           1078
#define IDC_BUTTON_OBJ_PROPERTY         1079
#define IDC_COMBO_OBJ_CLASS             1080
#define IDC_EDIT_OBJ_PARAM              1081
#define IDC_EDIT_OBJ_X                  1082
#define IDC_EDIT_OBJ_XP                 1083
#define IDC_EDIT_OBJ_Y                  1084
#define IDC_EDIT_OBJ_YP                 1085
#define ID_OPEN                         40001
#define ID_SAVE                         40002
#define ID_SAVEAS                       40003
#define ID_SAVEFINAL                    40004
#define ID_TESTGAME                     40005
#define ID_MAKE                         40008
#define ID_ABOUT                        40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
